const level1 = new Level(
    [
        new Golem,
        new Golem,
        new Golem,
        new Golem,
        new Endboss,
    ],
    [
        new Clouds()
    ],
    [
        new BackgroundObject('img/background-Winter/BG_01/Layers/Sky.png', -719, 0),
        new BackgroundObject('img/background-Winter/BG_01/Layers/BG.png', -719, 0),
        new BackgroundObject('img/background-Winter/BG_01/Layers/Middle.png', -719, 0),
        new BackgroundObject('img/background-Winter/BG_01/Layers/Foreground.png', -719, 0),
        new BackgroundObject('img/background-Winter/BG_01/Layers/Ground_01.png', -719, 0),
        new BackgroundObject('img/background-Winter/BG_01/Layers/Ground_02.png', -719, 0),
        new BackgroundObject('img/background-Winter/BG_01/Layers/Snow.png', -719, 0),
        new BackgroundObject('img/background-Winter/BG_01/Layers/Sky.png', 0, 0),
        new BackgroundObject('img/background-Winter/BG_01/Layers/BG.png', 0, 0),
        new BackgroundObject('img/background-Winter/BG_01/Layers/Middle.png', 0, 0),
        new BackgroundObject('img/background-Winter/BG_01/Layers/Foreground.png', 0, 0),
        new BackgroundObject('img/background-Winter/BG_01/Layers/Ground_01.png', 0, 0),
        new BackgroundObject('img/background-Winter/BG_01/Layers/Ground_02.png', 0, 0),
        new BackgroundObject('img/background-Winter/BG_01/Layers/Snow.png', 0, 0),
        new BackgroundObject('img/background-Winter/BG_01/Layers/Sky.png', 719, 0),
        new BackgroundObject('img/background-Winter/BG_01/Layers/BG.png', 719, 0),
        new BackgroundObject('img/background-Winter/BG_01/Layers/Middle.png', 719, 0),
        new BackgroundObject('img/background-Winter/BG_01/Layers/Foreground.png', 719, 0),
        new BackgroundObject('img/background-Winter/BG_01/Layers/Ground_01.png', 719, 0),
        new BackgroundObject('img/background-Winter/BG_01/Layers/Ground_02.png', 719, 0),
        new BackgroundObject('img/background-Winter/BG_01/Layers/Snow.png', 719, 0),
        new BackgroundObject('img/background-Winter/BG_01/Layers/Sky.png', 719 * 2, 0),
        new BackgroundObject('img/background-Winter/BG_01/Layers/BG.png', 719 * 2, 0),
        new BackgroundObject('img/background-Winter/BG_01/Layers/Middle.png', 719 * 2, 0),
        new BackgroundObject('img/background-Winter/BG_01/Layers/Foreground.png', 719 * 2, 0),
        new BackgroundObject('img/background-Winter/BG_01/Layers/Ground_01.png', 719 * 2, 0),
        new BackgroundObject('img/background-Winter/BG_01/Layers/Ground_02.png', 719 * 2, 0),
        new BackgroundObject('img/background-Winter/BG_01/Layers/Snow.png', 719 * 2, 0),
        new BackgroundObject('img/background-Winter/BG_01/Layers/Sky.png', 719 * 3, 0),
        new BackgroundObject('img/background-Winter/BG_01/Layers/BG.png', 719 * 3, 0),
        new BackgroundObject('img/background-Winter/BG_01/Layers/Middle.png', 719 * 3, 0),
        new BackgroundObject('img/background-Winter/BG_01/Layers/Foreground.png', 719 * 3, 0),
        new BackgroundObject('img/background-Winter/BG_01/Layers/Ground_01.png', 719 * 3, 0),
        new BackgroundObject('img/background-Winter/BG_01/Layers/Ground_02.png', 719 * 3, 0),
        new BackgroundObject('img/background-Winter/BG_01/Layers/Snow.png', 719 * 3, 0),

    ],
    [
        new Bottle('img/bottle-icons/PNG/background/1.png'),
        new Bottle('img/bottle-icons/PNG/background/50.png'),
        new Bottle('img/bottle-icons/PNG/background/50.png'),
        new Bottle('img/bottle-icons/PNG/background/50.png'),
        new Bottle('img/bottle-icons/PNG/background/50.png'),
        new Bottle('img/bottle-icons/PNG/background/50.png'),
        new Bottle('img/bottle-icons/PNG/background/50.png'),
        new Bottle('img/bottle-icons/PNG/background/50.png'),
        new Bottle('img/bottle-icons/PNG/background/50.png'),
        new Bottle('img/bottle-icons/PNG/background/50.png'),
        new Bottle('img/bottle-icons/PNG/background/50.png'),
    ]
);